---
apiVersion: v1
kind: Pod
metadata:
  name: required-caddy
  labels:
    app: caddy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values: [gpu]
  containers:
  - name: caddy
    image: docker.io/library/caddy
    ports:
    - containerPort: 80
    - containerPort: 443
    resources:
      limits:
        cpu: "2300m"
      requests:
        cpu: "2100m"
        memory: "1.5Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: preferred-caddy
  labels:
    app: caddy
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: workload
            operator: In
            values: [gpu]
  containers:
  - name: caddy
    image: docker.io/library/caddy
    ports:
    - containerPort: 80
    - containerPort: 443
    resources:
      limits:
        cpu: "2300m"
      requests:
        cpu: "2100m"
        memory: "1.5Gi"
