apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "oci-bv"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sglang
  template:
    metadata:
      labels:
        app: sglang
    spec:
      runtimeClassName: nvidia
      containers:
      - name: sglang
        image: lmsysorg/sglang:latest
        command: [ "python3", "-m", "sglang.launch_server" ]
        args:
        - "--model-path"
        - "Qwen/Qwen3-4B-Instruct-2507"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "30000"
        ports:
        - containerPort: 30000
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 8
            memory: 40Gi
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: model-storage
        livenessProbe:
          httpGet:
            path: /health
            port: 30000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health_generate
            port: 30000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: hf-cache
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-service
spec:
  selector:
    app: sglang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000
  type: LoadBalancer
